#!/bin/bash
rm -r ../../../../forum-angular-apache
#ng build --prod --base-href /forum-angular-apache/
ng build --configuration production --base-href /forum-angular-apache/
#ng build --base-href /forum-angular-apache/
#ng build --configuration production --base-href /forum-angular-apache/ --index
cp -fR dist/frontend ../../../../forum-angular-apache
#mv dist/frontend ../../forum-angular-apache
